<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE personas [
<!ELEMENT personas (persona+)>
 <!ELEMENT persona (nombre,mayor_edad?,ciudad)>
 <!ELEMENT nombre (#PCDATA)>
 <!ELEMENT mayor_edad EMPTY>
 <!ELEMENT ciudad (#PCDATA)>
]>
<personas>
  <persona>
    <nombre>Jose</nombre>
    <mayor_edad/>
    <ciudad>Cordoba</ciudad>
  </persona>
  <persona>
    <nombre>Dora</nombre>
    <ciudad>Medallin</ciudad>
  </persona>
</personas>